use_frameworks!

platform :ios, '12.0'
inhibit_all_warnings!

target 'XGCMain_Example' do
  pod 'XGCMain', :path => '../'

  target 'XGCMain_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
